{
  "0e03a480debcb54dd0ad4bed14f612d2" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "edd22d2fdba54977",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/38//#testresult/edd22d2fdba54977",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81be9bfd60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649183948593,
        "stop" : 1649183948593,
        "duration" : 0
      }
    } ]
  },
  "4c6a26788916d97b0c591def5d62e104" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "17cf4ecc9a11bd15",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/38//#testresult/17cf4ecc9a11bd15",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81bd586170>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649183949127,
        "stop" : 1649183949127,
        "duration" : 0
      }
    } ]
  },
  "b2e57dac307fb5f5a232440dbae3faf9" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "1f2fafe0e93dfd13",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/38//#testresult/1f2fafe0e93dfd13",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81bfa61c00>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649183948831,
        "stop" : 1649183948831,
        "duration" : 0
      }
    } ]
  },
  "65fd2b4dfcf9c1e5ba26298719a99a88" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "359733bff7cfc889",
      "reportUrl" : "https://rupu1906.github.io/docker-selenium/38//#testresult/359733bff7cfc889",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81bfcc48b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "time" : {
        "start" : 1649183948318,
        "stop" : 1649183948318,
        "duration" : 0
      }
    } ]
  }
}